#pragma once
#include <Runtime/Reflection/Type.h>

namespace Portakal
{
	GENERATE_PRIMITIVE(Char);
	GENERATE_PRIMITIVE(Bool8);
	GENERATE_PRIMITIVE(Byte);
	GENERATE_PRIMITIVE(UInt16);
	GENERATE_PRIMITIVE(UInt32);
	GENERATE_PRIMITIVE(UInt64);
	GENERATE_PRIMITIVE(Int16);
	GENERATE_PRIMITIVE(Int32);
	GENERATE_PRIMITIVE(Int64);
	GENERATE_PRIMITIVE(Float32);
	GENERATE_PRIMITIVE(Float64);

}
