#pragma once
#include <Runtime/Reflection/Type.h>

namespace Portakal
{
	GENERATE_PRIMITIVE(char);
	GENERATE_PRIMITIVE(byte);
	GENERATE_PRIMITIVE(uint16);
	GENERATE_PRIMITIVE(uint32);
	GENERATE_PRIMITIVE(uint64);
	GENERATE_PRIMITIVE(int16);
	GENERATE_PRIMITIVE(int32);
	GENERATE_PRIMITIVE(int64);
	GENERATE_PRIMITIVE(float);
	GENERATE_PRIMITIVE(double);
}
